version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: knowledgebase
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: knowledgebase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knowledgebase"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://knowledgebase:password123@postgres:5432/knowledgebase
      JWT_SECRET: your-super-secret-jwt-key-here
      OPENAI_API_KEY: your-openai-api-key-here
      NODE_ENV: production
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
